stages:
- build
- deploy

before_script:
  - PROJECT=${PWD##*/}
  # DOCKER_REPO can alternatively be setup @ gitlab variables
  - DOCKER_REPO="haphaxrd.io:5000"
  - echo $PROJECT
  - echo $CI_BUILD_ID
  - echo $CI_BUILD_TAG
  - source ./build/common.sh

build_job:
  stage: build
  script:
    - k::build

deploy_job:
  stage: deploy
  script:
    -  k::upgrade