stages:
- build
- deploy

before_script:
  - PROJECT=${PWD##*/}
  - echo $PROJECT
  - echo $CI_BUILD_ID
  - source ./build/common.sh

build_job:
  stage: build
  script:
    - docker build -t haphaxrd.io:5000/$PROJECT .
    - ID="$(docker images | grep 'haphaxrd.io:5000/'$PROJECT | head -n 1 | awk '{print $3}')"
    - docker tag $ID haphaxrd.io:5000/$PROJECT:$CI_BUILD_ID
    - docker push haphaxrd.io:5000/$PROJECT

deploy_job:
  stage: deploy
  script:
    -  k::upgrade