apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-gitlab
spec:
  replicas: 1
  selector:
    name: kube-gitlab
  template:
    metadata:
      labels:
        name: kube-gitlab
        role: demo
    spec:
      containers:
      - name: kube-gitlab
        image: haphaxrd.io:5000/kube-gitlab:latest #override this with your own "private-docker-repo:5000"
        ports:
          - name: https
            containerPort: 443
          - name: http
            containerPort: 80