apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
        role: tools
    spec:
      containers:
      - name: nginx
        image: haphaxrd.io:5000/nginx:latest
        ports:
          - name: https
            containerPort: 443
          - name: http
            containerPort: 80