apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  clusterIP: 10.100.13.37
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: nginx
  type: NodePort