apiVersion: v1
kind: Service
metadata:
  name: kube-gitlab
spec:
  clusterIP: 10.100.13.37
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    name: kube-gitlab
  type: NodePort